- name: Ensure the directory to copy the files to exists
  file:
    path: /etc/kubernetes/pki
    state: directory

- name: Copy k8 certificates from master 0 to other masters
  copy:
    src: "{{ item }}"
    dest: "/etc/kubernetes/pki/{{ item }}"
  with_items:
     - ca.crt
     - ca.key
     - sa.key
     - sa.pub