- name: Get etcd certificates from master 0
  fetch:
    src: "/etc/kubernetes/pki/etcd/{{ item }}"
    dest: ../roles/send_etcd_certificates/files/
    flat: yes
  with_items:
     - ca.pem
     - ca-key.pem
     - client.pem
     - client-key.pem
     - ca-config.json