- name: Ensure the directory to copy the files to exists
  file:
    path: /etc/pki/etcd
    state: directory

- name: Copy all etcd certificates to targets
  copy:
    src: "{{ item }}"
    dest: "/etc/pki/etcd/{{ item }}"
  with_items:
     - ca.pem
     - ca-key.pem
     - client.pem
     - client-key.pem
     - ca-config.json
  when: not client_only

- name: Copy client etcd certificates to targets
  copy:
    src: "{{ item }}"
    dest: "/etc/pki/etcd/{{ item }}"
  with_items:
     - ca.pem
     - client.pem
     - client-key.pem
     - ca-config.json
  when: client_only