- name: Ensure the directory to copy the configs to exists
  file:
    path: /opt/haproxy
    state: directory

- name: Ascertain if existing configurations require an update
  script: configuration_requires_update.sh
  become: yes
  environment:
    INVENTORY: "{{ masters_peer_inventory_hostnames }}"
  register: configuration_requires_update

- template:
    src: config.j2
    dest: /opt/haproxy/haproxy.cfg
    mode: 0644

- name: Starts haproxy
  script: setup.sh
  become: yes
  environment:
    ARCHITECTURE: "{{ cpu_architecture }}"
    UPDATED_CONFIGURATION: "{{ configuration_requires_update.stdout }}"