- name: Get k8 certificates from master 0
  fetch:
    src: "/etc/kubernetes/pki/{{ item }}"
    dest: ../roles/kubernetes/masters/send_certificates/files/
    flat: yes
  with_items:
     - ca.crt
     - ca.key
     - sa.key
     - sa.pub