---
- name: Determine host's peer ip
  set_fact:
    peer_ip: "{{ hostvars[inventory_hostname]['internal_ip'] | default(hostvars[inventory_hostname]['ansible_default_ipv4']['address']) }}"

- name: Determine kubernetes' admin user
  set_fact:
    kubernetes_admin: "{{ ansible_user_id }}"
  when: kubernetes_admin is undefined

- name: Flag amd64 architecture
  set_fact:
    cpu_architecture: "amd64"
  when: "'x86_64' in ansible_architecture"

- name: Flag arm64 architecture
  set_fact:
    cpu_architecture: "arm64"
  when: "'arm64' in ansible_architecture"

- name: Fail if cpu architecture is not supported
  fail:
    msg: "The cpu architecture of your machines is not supported. Only amd64 and arm64 cpu architectures are supported by this playbook."
  when: cpu_architecture is undefined
