- name: Get etcd certificates from store 0
  fetch:
    src: "/etc/pki/etcd/{{ item }}"
    dest: ../roles/kubernetes/etcd/send_certificates/files/
    flat: yes
  with_items:
     - ca.pem
     - ca-key.pem
     - client.pem
     - client-key.pem
     - ca-config.json