- name: Ensure the directory to copy the files to exists
  file:
    path: /etc/kubernetes/pki/etcd
    state: directory

- name: Copy etcd certificates from master 0 to other masters
  copy:
    src: "{{ item }}"
    dest: "/etc/kubernetes/pki/etcd/{{ item }}"
  with_items:
     - ca.pem
     - ca-key.pem
     - client.pem
     - client-key.pem
     - ca-config.json