---
- name: Set hosts facts
  hosts: all
  roles:
  - { role: ../roles/set_host_facts, become: true }

- name: Install Kubeadm base dependencies
  hosts: all
  roles:
  - { role: ../roles/docker, become: true }
  - { role: ../roles/kubernetes/kubeadm, become: true }