---
- name: Set hosts facts
  hosts: all
  roles:
  - { role: ../roles/kubernetes/set_host_facts, become: true }

- name: Set api_url to load balancer ip if not defined
  hosts: masters
  tasks:
  - set_fact: 
      api_url: "{{ hostvars[groups['load_balancers'][0]].peer_ip }}"
    when: api_url is undefined

- name: Prepare inventory list for masters
  hosts: masters
  tasks:
  - set_fact: 
      inventory_hostnames: "{{ groups['masters'] | join(' ') }}"

- name: Prepare peer inventory list for masters
  hosts: masters
  tasks:
  - set_fact: 
      peer_inventory_hostnames: "{{ groups['masters'] | map('extract', hostvars, 'peer_ip') | list | join(' ') }}"

- name: Reboot etcd with the right version if it doesn't match the kubeadm version
  hosts: masters
  serial: 1
  roles:
  - { role: ../roles/kubernetes/etcd/matches_kubeadm_version, become: true }
  - role: ../roles/kubernetes/etcd/shutdown
    become: true
    when: etcd_matches_kubeadm_version.stdout == "no"
  - role: ../roles/kubernetes/etcd/launch
    become: true
    when: etcd_matches_kubeadm_version.stdout == "no"