---

- name: Set hosts facts
  hosts: all
  roles:
  - { role: ../roles/set_host_facts, become: true }

- name: Install Master
  hosts: masters
  roles:
  - { role: ../roles/docker, become: true }
  - { role: ../roles/kubeadm, become: true }
  - { role: ../roles/k8-master-flannel, become: true }
  - { role: ../roles/k8-store-join-command, become: true }

- name: Install Workers
  hosts: workers
  roles:
  - { role: ../roles/docker, become: true }
  - { role: ../roles/kubeadm, become: true }
  - { role: ../roles/k8-join-master, become: true }
