---

- name: Set hosts facts
  hosts: all
  roles:
  - { role: ../roles/kubernetes/set_host_facts, become: true }

- name: Install Master
  hosts: masters
  roles:
  - { role: ../roles/docker, become: true }
  - { role: ../roles/kubernetes/kubeadm, become: true }
  - { role: ../roles/kubernetes/masters/single_master_flannel, become: true }
  - { role: ../roles/kubernetes/masters/store_join_command, become: true }

- name: Install Workers
  hosts: workers
  roles:
  - { role: ../roles/docker, become: true }
  - { role: ../roles/kubernetes/kubeadm, become: true }
  - { role: ../roles/kubernetes/workers/join, become: true }
